// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmk4hCLA6_E7ZyqSrn_J-JQKbnxb0gc5w',
    appId: '1:988455059776:web:ed457084e4c75d5e8bfaa5',
    messagingSenderId: '988455059776',
    projectId: 'grabarber-d305d',
    authDomain: 'grabarber-d305d.firebaseapp.com',
    storageBucket: 'grabarber-d305d.appspot.com',
    measurementId: 'G-5WXBQPZCKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPhz3fzFlJ9Wfz_UeVvVB8l7S98sEido',
    appId: '1:988455059776:android:cccc7362bd8396d58bfaa5',
    messagingSenderId: '988455059776',
    projectId: 'grabarber-d305d',
    storageBucket: 'grabarber-d305d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlxQtBZ00KqOJOgnnpow7_x1okUbX8vU8',
    appId: '1:988455059776:ios:98c54f1d4f9023d58bfaa5',
    messagingSenderId: '988455059776',
    projectId: 'grabarber-d305d',
    storageBucket: 'grabarber-d305d.appspot.com',
    iosBundleId: 'com.example.androidProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlxQtBZ00KqOJOgnnpow7_x1okUbX8vU8',
    appId: '1:988455059776:ios:1fe6e0c9dfc7349e8bfaa5',
    messagingSenderId: '988455059776',
    projectId: 'grabarber-d305d',
    storageBucket: 'grabarber-d305d.appspot.com',
    iosBundleId: 'com.example.androidProject.RunnerTests',
  );
}
